spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
              900783094046-ofbmg9vjjj3s7rlothspmhar185g72il.apps.googleusercontent.com
            client-secret:
              HjY7S9-KUpHrjLODz535PY9g